### ISSUE TITLE
Nested booleans cannot be overwritten to false

### ISSUE THREAD

**Issue by bessey** [rubyconfig/config#166]
Steps to reproduce:
```yaml
# settings.yml
my_thing:
  enabled: true
other_thing_enabled: true

# settings/development.yml
my_thing:
  enabled: false
other_thing_enabled: false
```

```
$ bin/rails c development
Settings.my_thing.enabled
=> true
Settings.other_thing_enabled
=> false
```

This bug has caught me several times and seems highly unintuitive.
