### ISSUE TITLE
Is it possible to reference another configuration in a YAML file? 

### ISSUE THREAD

**Issue by pecuerre** [rubyconfig/config#302]
Let me explain. I think the title might not be clear.

I would like to do something like:

```yaml
color:
  front: '000000'
  back: 'FFFFFF'
text:
  size: 10
  family: Arial
  color: <%= Settings.color.front %> # or some similar syntax
```

but when I put this it says `uninitialized constant Settings`.

is it possible to do that? is it a workaround some how?

basically what i want to do is define one value that depends on another value.

**Comment by cjlarose** [comment]
YAML itself has support for anchors and references, so in your case you can do something like this:

```yaml
color:
  front: &front-color '000000'
  back: 'FFFFFF'
text:
  size: 10
  family: Arial
  color: *front-color
```

See the [YAML 1.2 specification section 6.9.2](https://yaml.org/spec/1.2/spec.html#id2785586) for more details
